-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           5.7.9-log - MySQL Community Server (GPL)
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              9.5.0.5196
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Copiando estrutura para tabela myouro.clientes
CREATE TABLE IF NOT EXISTS `clientes` (
  `CODCLI` int(11) NOT NULL AUTO_INCREMENT,
  `NOMECLI` varchar(50) DEFAULT NULL,
  `NOMEFANTASIA` varchar(50) NOT NULL DEFAULT '',
  `CNPJCLI` varchar(20) DEFAULT NULL,
  `ULTCOMPRA` date DEFAULT NULL,
  `VLRCOMPRA` double DEFAULT NULL,
  `ULTPGTO` date DEFAULT NULL,
  `VLRPGTO` double DEFAULT NULL,
  `CODSETOR` int(11) DEFAULT NULL,
  `RGCLI` varchar(18) DEFAULT NULL,
  `RGEMISSOR` varchar(10) DEFAULT NULL,
  `RGUF` char(2) DEFAULT NULL,
  `SEXO` char(2) DEFAULT 'M',
  `NATURALIDADE` varchar(30) DEFAULT NULL,
  `SENHA` varchar(30) DEFAULT NULL,
  `DTNASC` date DEFAULT NULL,
  `DIAPGTO` char(2) DEFAULT NULL,
  `CODLOJA` varchar(4) DEFAULT NULL,
  `BLOQUEIO` char(1) DEFAULT 'N',
  `CPFCLI` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CODCLI`),
  KEY `CNPJCLI` (`CNPJCLI`),
  KEY `CODCLI` (`CODCLI`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=419 ROW_FORMAT=DYNAMIC;

-- Copiando dados para a tabela myouro.clientes: ~8 rows (aproximadamente)
/*!40000 ALTER TABLE `clientes` DISABLE KEYS */;
INSERT INTO `clientes` (`CODCLI`, `NOMECLI`, `NOMEFANTASIA`, `CNPJCLI`, `ULTCOMPRA`, `VLRCOMPRA`, `ULTPGTO`, `VLRPGTO`, `CODSETOR`, `RGCLI`, `RGEMISSOR`, `RGUF`, `SEXO`, `NATURALIDADE`, `SENHA`, `DTNASC`, `DIAPGTO`, `CODLOJA`, `BLOQUEIO`, `CPFCLI`) VALUES
	(16, 'WAGNER OLIVEIRA DA COSTA', '', '04.918.478/0001-56', NULL, NULL, NULL, NULL, NULL, '463410944', NULL, NULL, 'F', NULL, NULL, NULL, NULL, NULL, 'N', '898.487.070-69'),
	(17, 'VSM WAGNER TESTE 001002', '', '74.918.478/0001-57', NULL, NULL, NULL, NULL, NULL, '1111111111', NULL, NULL, 'F', NULL, NULL, NULL, NULL, NULL, 'N', '898.487.070-69'),
	(18, 'SISTEMA VSM INTEGRADO COM CADASTRO', '', '94.918.478/0001-56', NULL, NULL, NULL, NULL, NULL, '1111111', NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, 'N', '898.487.070-69'),
	(24, 'TESTE', '', '48.136.870/0001-19', NULL, NULL, NULL, NULL, NULL, 'qqqqq', NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, 'N', '898.487.070-69'),
	(26, 'teste 31', '', '48.160.186/0001-72', NULL, NULL, NULL, NULL, NULL, '444', NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, 'N', NULL),
	(27, 'teste vsm 45', '', NULL, NULL, NULL, NULL, NULL, NULL, 'werwerwer', NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, 'N', '223.131.232-32'),
	(28, 'TESTE 157', '', NULL, NULL, NULL, NULL, NULL, NULL, '1111111111111', NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, 'N', '260.682.210-24'),
	(29, 'teste 11:09', '', '48.160.186/0001-72', NULL, NULL, NULL, NULL, NULL, '11111111111', NULL, NULL, 'M', NULL, NULL, NULL, NULL, NULL, 'N', NULL);
/*!40000 ALTER TABLE `clientes` ENABLE KEYS */;

-- Copiando estrutura para tabela myouro.endcli
CREATE TABLE IF NOT EXISTS `endcli` (
  `IDENDCLI` int(11) NOT NULL AUTO_INCREMENT,
  `CODCLI` int(11) NOT NULL DEFAULT '0',
  `TIPOEND` varchar(15) DEFAULT NULL,
  `CEPCLI` varchar(11) DEFAULT NULL,
  `ENDCLI` varchar(50) DEFAULT NULL,
  `NUMCLI` varchar(10) DEFAULT NULL,
  `BAIRROCLI` varchar(30) DEFAULT NULL,
  `CODCID` int(11) NOT NULL DEFAULT '0',
  `COMPLEMENTO` varchar(50) DEFAULT NULL,
  `NUMERO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`IDENDCLI`),
  KEY `CODCLI` (`CODCLI`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=197 ROW_FORMAT=DYNAMIC;

-- Copiando dados para a tabela myouro.endcli: ~5 rows (aproximadamente)
/*!40000 ALTER TABLE `endcli` DISABLE KEYS */;
INSERT INTO `endcli` (`IDENDCLI`, `CODCLI`, `TIPOEND`, `CEPCLI`, `ENDCLI`, `NUMCLI`, `BAIRROCLI`, `CODCID`, `COMPLEMENTO`, `NUMERO`) VALUES
	(1, 16, 'teste', '19.803-240', 'TESTE 2020', NULL, NULL, 0, NULL, NULL),
	(4, 16, 'RUA', '19.803-240', 'RUA CATETO, 190', NULL, 'PRUDENCIANA', 0, 'ASSIS', NULL),
	(5, 17, 'RES', '19.803-240', 'RUA CATETO, 190', NULL, 'CENTRO', 0, NULL, NULL),
	(6, 18, 'EUA', '19.803-240', 'RUA CATETO, 190', NULL, 'Prudenciana', 0, 'Assis', NULL),
	(8, 29, 'RES', '19.803-240', 'RUA CATETO, 190', NULL, 'CENTRO', 0, 'Assis', NULL);
/*!40000 ALTER TABLE `endcli` ENABLE KEYS */;

-- Copiando estrutura para tabela myouro.telcli
CREATE TABLE IF NOT EXISTS `telcli` (
  `IDTELCLI` int(11) NOT NULL AUTO_INCREMENT,
  `CODCLI` int(11) NOT NULL DEFAULT '0',
  `TIPOTEL` varchar(30) DEFAULT NULL,
  `TELEFONE` varchar(14) NOT NULL DEFAULT '',
  `OBSTEL` varchar(100) DEFAULT NULL,
  `IDOPERADORATELEFONIA` int(11) DEFAULT NULL,
  PRIMARY KEY (`IDTELCLI`),
  UNIQUE KEY `IDTELCLI` (`IDTELCLI`),
  KEY `CODCLI` (`CODCLI`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=63 ROW_FORMAT=DYNAMIC;

-- Copiando dados para a tabela myouro.telcli: ~4 rows (aproximadamente)
/*!40000 ALTER TABLE `telcli` DISABLE KEYS */;
INSERT INTO `telcli` (`IDTELCLI`, `CODCLI`, `TIPOTEL`, `TELEFONE`, `OBSTEL`, `IDOPERADORATELEFONIA`) VALUES
	(3, 18, 'Celular', '9999999', NULL, NULL),
	(4, 18, 'Comercial', '1111111', NULL, NULL),
	(5, 16, 'res', '(18)99999-9999', NULL, NULL),
	(6, 16, 'com', '(18)99889-9888', NULL, NULL);
/*!40000 ALTER TABLE `telcli` ENABLE KEYS */;

-- Copiando estrutura para tabela myouro.vendedores
CREATE TABLE IF NOT EXISTS `vendedores` (
  `CODVEND` int(11) NOT NULL AUTO_INCREMENT,
  `NOMEVEND` varchar(50) DEFAULT NULL,
  `APELIDO` varchar(30) DEFAULT NULL,
  `SENHAVEND` varchar(12) NOT NULL DEFAULT '',
  `FUNCAOVEND` char(1) NOT NULL DEFAULT 'V',
  `CODLOJA` int(11) NOT NULL DEFAULT '0',
  `NIVEL` int(1) DEFAULT '0',
  `IDPERFIL` int(11) DEFAULT NULL,
  `SITUACAO` char(1) DEFAULT '',
  `SENHACOLAB` varchar(255) NOT NULL DEFAULT '',
  `SENHAEXPIRADA` char(1) DEFAULT 'N',
  `DATANASC` date DEFAULT NULL,
  `CEPVEND` varchar(9) DEFAULT NULL,
  `ENDVEND` varchar(50) DEFAULT NULL,
  `NUMVEND` varchar(10) DEFAULT NULL,
  `BAIRROVEND` varchar(50) DEFAULT NULL,
  `CODCID` int(11) DEFAULT NULL,
  `FONERES` varchar(14) DEFAULT NULL,
  `FONECEL` varchar(14) DEFAULT NULL,
  `DATAADMISSAO` date DEFAULT NULL,
  `DATADEMISSAO` date DEFAULT NULL,
  `QTDETENTATIVASEX` int(11) DEFAULT '0',
  `EMAIL` varchar(40) DEFAULT NULL,
  `ATENDSIMULTANEO` tinyint(2) NOT NULL DEFAULT '1',
  `STATUS` char(3) DEFAULT 'OFF',
  PRIMARY KEY (`CODVEND`),
  UNIQUE KEY `CODVEND` (`CODVEND`),
  KEY `NOMEVEND` (`NOMEVEND`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1 AVG_ROW_LENGTH=287 ROW_FORMAT=DYNAMIC;

-- Copiando dados para a tabela myouro.vendedores: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `vendedores` DISABLE KEYS */;
INSERT INTO `vendedores` (`CODVEND`, `NOMEVEND`, `APELIDO`, `SENHAVEND`, `FUNCAOVEND`, `CODLOJA`, `NIVEL`, `IDPERFIL`, `SITUACAO`, `SENHACOLAB`, `SENHAEXPIRADA`, `DATANASC`, `CEPVEND`, `ENDVEND`, `NUMVEND`, `BAIRROVEND`, `CODCID`, `FONERES`, `FONECEL`, `DATAADMISSAO`, `DATADEMISSAO`, `QTDETENTATIVASEX`, `EMAIL`, `ATENDSIMULTANEO`, `STATUS`) VALUES
	(1, 'VSM', 'CASE', 'demo', 'V', 1, 1, 1, 'A', 'demo', 'N', '0000-00-00', '19803240', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 1, 'OFF');
/*!40000 ALTER TABLE `vendedores` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
